In [ ]:
import pandas as pd

df = pd.read_excel(r"D:\OC\sales order list 20260816.xlsx")
# df = pd.read_excel(r"D:\OC\sales order list.xlsx")
df1=pd.read_excel(r"D:\PythonProjects\sales-order-parser\data\raw\service.xlsx")
df1=pd.read_csv(r"D:\PythonProjects\sales-order-parser\data\raw\service.csv")

df1.shape
df1.sort_values(by=['Sales Agent']).head(10)
# df1["Customer"].nunique()

In [ ]:
df1["Sales Agent"].nunique()
df1.groupby("Sales Agent")["Total Fee"].sum()

df.groupby("agent")["amount"].sum()

In [43]:
df.loc[df['agent'].str.len() > 30]

,sales_order_no,document_date,customer_no,customer_name,customer_address,customer_postcode,customer_city,customer_country,agent,reference_quote_no,...,pos_number,item_description,item_details,quantity,unit,unit_price,amount,discount,tax_code,subtotal_amount
342,2015-864008,2015-09-01,DCN000090,"artax Audit & Tax Consulting (Shanghai) Co., Ltd.","German Centre, Service Apartement, Room 602 88...",201203.0,SHANGHAI,CHINA,Software for the virtual server,NaN,...,1,### Onetime Investment ###,NaN,0.0,NaN,0.0,0.0,0.0,NaN,24810.00
343,2015-864008,2015-09-01,DCN000090,"artax Audit & Tax Consulting (Shanghai) Co., Ltd.","German Centre, Service Apartement, Room 602 88...",201203.0,SHANGHAI,CHINA,Software for the virtual server,NaN,...,1.1,DD vitural dedicated server,"Installation, Konfiguration OS",1.0,Piece,3000.0,3000.0,0.0,910.0,24810.00
344,2015-864008,2015-09-01,DCN000090,"artax Audit & Tax Consulting (Shanghai) Co., Ltd.","German Centre, Service Apartement, Room 602 88...",201203.0,SHANGHAI,CHINA,Software for the virtual server,NaN,...,1.2,DD vitural dedicated server,Data Backup\n1.3 Remote access terminal s...,1.0,Piece,3000.0,3000.0,0.0,910.0,24810.00
345,2015-864008,2015-09-01,DCN000090,"artax Audit & Tax Consulting (Shanghai) Co., Ltd.","German Centre, Service Apartement, Room 602 88...",201203.0,SHANGHAI,CHINA,Software for the virtual server,NaN,...,1.3.1,DD datacenter hosting,Installation\nDD datacenter hosting\nProvision...,1.0,Piece,900.0,900.0,0.0,910.0,24810.00
346,2015-864008,2015-09-01,DCN000090,"artax Audit & Tax Consulting (Shanghai) Co., Ltd.","German Centre, Service Apartement, Room 602 88...",201203.0,SHANGHAI,CHINA,Software for the virtual server,NaN,...,1.3.2,Backup Strategie,Backup Management\n1.3 Remote access term...,1.0,Piece,450.0,450.0,0.0,910.0,24810.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11024,2025-864199,2025-09-29,DCN000201,"GELITA (Pingyang) Gelatine Co., Ltd.","Dongjiang Village, Qiancang Town,",325802.0,PINGYANG,CHINA,subscription renewal for ...,2025-863324,...,1,"*** 1 year *** 94.062,84",NaN,0.0,NaN,0.0,0.0,0.0,NaN,108457.64
11025,2025-864199,2025-09-29,DCN000201,"GELITA (Pingyang) Gelatine Co., Ltd.","Dongjiang Village, Qiancang Town,",325802.0,PINGYANG,CHINA,subscription renewal for ...,2025-863324,...,2,*** SD WAN**,NaN,0.0,NaN,0.0,0.0,0.0,NaN,108457.64
11026,2025-864199,2025-09-29,DCN000201,"GELITA (Pingyang) Gelatine Co., Ltd.","Dongjiang Village, Qiancang Town,",325802.0,PINGYANG,CHINA,subscription renewal for ...,2025-863324,...,2.1,"SD-WAN subscription for dev ices in HA pair,PA...",1 year\nnew end date after ordering:29th.Dec.2026,2.0,piece,7420.0,14840.0,-445.2,903.0,108457.64
11027,2025-864199,2025-09-29,DCN000201,"GELITA (Pingyang) Gelatine Co., Ltd.","Dongjiang Village, Qiancang Town,",325802.0,PINGYANG,CHINA,subscription renewal for ...,2025-863324,...,2,"*** SD WAN** 14.394,80",NaN,0.0,NaN,0.0,0.0,0.0,NaN,108457.64
11028,2025-864199,2025-09-29,DCN000201,"GELITA (Pingyang) Gelatine Co., Ltd.","Dongjiang Village, Qiancang Town,",325802.0,PINGYANG,CHINA,subscription renewal for ...,2025-863324,...,3,Supply of services,assit to active the license,1.0,Piece,1000.0,1000.0,-1000.0,910.0,108457.64

In [ ]:
df["sales_order_no"].nunique()
df.groupby("sales_order_no").size()
df.isna().sum()

In [47]:
line="hjhk china"
line.split()[-1]

'china'

In [34]:
item_totals = (
    df.groupby("sales_order_no")["amount"]
      .sum()
)

item_discount_totals= (
    df.groupby("sales_order_no")["discount"]
      .sum()
)
subtotals = (
    df.groupby("sales_order_no")["subtotal_amount"]
      .first()
)

check = pd.DataFrame({
    "item_total": item_totals,
    "item_discount_total":item_discount_totals,
    "subtotal": subtotals
})

check["difference"] = (
    check["subtotal"] - (check["item_total"]+check["item_discount_total"])
)

check

                item_total  item_discount_total    subtotal  difference
sales_order_no
2014-864061        7500.00                  0.0     7500.00         0.0
2014-864069      453223.00                  0.0   453223.00         0.0
2014-864105     1094975.42                  0.0  1094975.42         0.0
2014-864136       32200.00                  0.0    32200.00         0.0
2014-864143        5439.00                  0.0     5439.00         0.0
...                    ...                  ...         ...         ...
2026-864111        4795.00               -450.0     4345.00         0.0
2026-864115       14420.00                  0.0    14420.00         0.0
2026-864117        2600.00                  0.0     2600.00         0.0
2026-864118         745.00               -225.0      520.00         0.0
2026-864120       36891.00                  0.0    36891.00         0.0

[1722 rows x 4 columns]

In [35]:
check[check["difference"].abs() > 0.01]

Empty DataFrame
Columns: [item_total, item_discount_total, subtotal, difference]
Index: []

In [ ]:
check[check["difference"].abs() > 0.01].head(20)